package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"text/template"
)

const serviceUsage = `Usage:
  cometseed [-config FILE] service <action> [flags]

Actions:
  print       print the unit file that install would write
  install     write the unit, reload systemd, enable and start it
  update      rewrite the unit (new binary or config path), reload and restart it
  uninstall   stop, disable and remove the unit
  status      show systemctl status

Flags:
`

var unitTemplate = template.Must(template.New("unit").Parse(`# Generated by cometseed {{.Version}}: run "cometseed service update" to regenerate.
[Unit]
Description=cometseed - stateless CometBFT seed node ({{.Networks}})
After=network-online.target
Wants=network-online.target

[Service]
{{- if .RunAs}}
User={{.RunAs}}
{{- end}}
ExecStart={{.Binary}} -config {{.Config}}
Restart=always
RestartSec=10
LimitNOFILE=65536
{{- if .System}}
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
{{- end}}

[Install]
WantedBy={{if .System}}multi-user.target{{else}}default.target{{end}}
`))

type unitData struct {
	Version  string
	Networks string
	Binary   string
	Config   string
	RunAs    string
	System   bool
}

type serviceOpts struct {
	name    string
	system  bool
	binary  string
	runAs   string
	noStart bool
}

func serviceCmd(configPath string, args []string) error {
	fs := flag.NewFlagSet("service", flag.ExitOnError)
	o := serviceOpts{}
	fs.StringVar(&o.name, "name", "cometseed", "unit name")
	fs.BoolVar(&o.system, "system", os.Geteuid() == 0, "system unit in /etc/systemd/system (needs root) instead of a user unit")
	fs.StringVar(&o.binary, "binary", "", "binary path in ExecStart (default: this executable)")
	fs.StringVar(&o.runAs, "run-as", "", "User= of a system unit (default: $SUDO_USER, else the current user)")
	fs.BoolVar(&o.noStart, "no-start", false, "install without enabling and starting")
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, serviceUsage)
		fs.PrintDefaults()
	}
	if len(args) == 0 {
		fs.Usage()
		return errors.New("missing service action")
	}
	action := args[0]
	_ = fs.Parse(args[1:])

	switch action {
	case "print", "install", "update":
		unit, err := renderUnit(configPath, o)
		if err != nil {
			return err
		}
		if action == "print" {
			fmt.Print(unit)
			return nil
		}
		return installUnit(unit, o, action == "update")
	case "uninstall":
		return uninstallUnit(o)
	case "status":
		return systemctl(o, true, "status", "--no-pager", o.name)
	default:
		fs.Usage()
		return fmt.Errorf("unknown service action %q", action)
	}
}

// renderUnit validates the configuration before writing anything, so a unit
// never points at a config that cannot start.
func renderUnit(configPath string, o serviceOpts) (string, error) {
	cfgAbs, err := filepath.Abs(configPath)
	if err != nil {
		return "", err
	}
	c, err := LoadConfig(cfgAbs)
	if err != nil {
		return "", fmt.Errorf("%s: %w", cfgAbs, err)
	}
	nets, err := c.ResolveNetworks()
	if err != nil {
		return "", err
	}
	names := make([]string, len(nets))
	for i, n := range nets {
		names[i] = n.Name
	}

	bin := o.binary
	if bin == "" {
		if bin, err = os.Executable(); err != nil {
			return "", err
		}
		if resolved, err := filepath.EvalSymlinks(bin); err == nil {
			bin = resolved
		}
	}
	if bin, err = filepath.Abs(bin); err != nil {
		return "", err
	}

	d := unitData{Version: buildVersion, Networks: strings.Join(names, ", "), Binary: bin, Config: cfgAbs, System: o.system}
	if o.system {
		d.RunAs = o.runAs
		if d.RunAs == "" {
			d.RunAs = os.Getenv("SUDO_USER")
		}
		if d.RunAs == "" {
			if u, err := user.Current(); err == nil {
				d.RunAs = u.Username
			}
		}
		if d.RunAs == "root" {
			fmt.Fprintln(os.Stderr, "warning: the system unit runs cometseed as root; use -run-as to pick an unprivileged user")
		}
	}
	var buf bytes.Buffer
	if err := unitTemplate.Execute(&buf, d); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func unitPath(o serviceOpts) (string, error) {
	if o.system {
		return filepath.Join("/etc/systemd/system", o.name+".service"), nil
	}
	cfgDir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(cfgDir, "systemd", "user", o.name+".service"), nil
}

func installUnit(unit string, o serviceOpts, update bool) error {
	path, err := unitPath(o)
	if err != nil {
		return err
	}
	old, readErr := os.ReadFile(path)
	exists := readErr == nil
	if update && !exists {
		return fmt.Errorf("%s does not exist: use install", path)
	}
	if !update && exists && string(old) != unit {
		return fmt.Errorf("%s already exists with different content: use update", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(unit), 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", path)

	if err := systemctl(o, false, "daemon-reload"); err != nil {
		return err
	}
	switch {
	case update:
		if err := systemctl(o, false, "restart", o.name); err != nil {
			return err
		}
		fmt.Println("restarted", o.name)
	case o.noStart:
		fmt.Printf("not started: run systemctl %s enable --now %s\n", scope(o), o.name)
	default:
		if err := systemctl(o, false, "enable", "--now", o.name); err != nil {
			return err
		}
		fmt.Println("enabled and started", o.name)
	}
	if !o.system {
		warnLinger()
	}
	return nil
}

func uninstallUnit(o serviceOpts) error {
	path, err := unitPath(o)
	if err != nil {
		return err
	}
	if _, err := os.Stat(path); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	_ = systemctl(o, false, "disable", "--now", o.name)
	if err := os.Remove(path); err != nil {
		return err
	}
	fmt.Println("removed", path)
	return systemctl(o, false, "daemon-reload")
}

func scope(o serviceOpts) string {
	if o.system {
		return ""
	}
	return "--user"
}

func systemctl(o serviceOpts, passthrough bool, args ...string) error {
	if !o.system {
		args = append([]string{"--user"}, args...)
	}
	cmd := exec.Command("systemctl", args...)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	err := cmd.Run()
	if err != nil && !passthrough {
		return fmt.Errorf("systemctl %s: %w", strings.Join(args, " "), err)
	}
	return nil
}

// warnLinger reminds that a user unit stops at logout unless lingering is on.
func warnLinger() {
	u, err := user.Current()
	if err != nil {
		return
	}
	out, err := exec.Command("loginctl", "show-user", u.Username, "-p", "Linger", "--value").Output()
	if err == nil && strings.TrimSpace(string(out)) == "no" {
		fmt.Printf("note: lingering is off, the seed stops when %s logs out: run `loginctl enable-linger %s`\n", u.Username, u.Username)
	}
}
